name: ci-test-tag

on: # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
  push: { tags: [ "v*" ] } # use `v0.0.0` tag pattern

jobs:
  test-tag: # job id
    timeout-minutes: 15
    strategy:
      fail-fast: false # allow all test to run to the end
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        node-version: [ "14.x", "16.x" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v2", with: { node-version: "${{ matrix.node-version }}" } } # https://github.com/actions/setup-node
      - run: npx @dr-js/dev@0.4 -eI .github/ci-patch.js
      - run: npm8 ci
      - run: npm test

  publish-tag: # job id
    needs: [ "test-tag" ] # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
    timeout-minutes: 15
    runs-on: "ubuntu-latest"
    steps:
      - { uses: "actions/checkout@v2" } # https://github.com/actions/checkout
      - { uses: "actions/setup-node@v2", with: { node-version: "16.x" } } # https://github.com/actions/setup-node
      - run: npx @dr-js/dev@0.4 -eI .github/ci-patch.js
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN_DR_JS }}" > .npmrc
      - run: npm8 ci
      - run: npm run script-publish
